project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "My Website"
  repo-url: https://github.com/lter/workshop-quarto
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
    right: 
      - icon: github
        href: https://github.com/lter/workshop-quarto
  page-footer: 
    center: "Copyright 2025, LTER Network"
    background: secondary

format:
  html:
    toc: true
    link-external-newwindow: true
    link-external-icon: false